spring:
  profiles:
    active: test
  datasource:
    url: ${env.JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${env.JDBC_DATABASE_USERNAME}
    password: ${env.JDBC_DATABASE_PASSWORD}